<a href="https://colab.research.google.com/github/sanjaynagi/AnoExpress/blob/main/workflow/notebooks/Utility_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install anoexpress -q

In [2]:
import anoexpress as xpress

### AnoExpress utility functions

In [11]:
?xpress.data

In [9]:
### load fold-change data
fc_data = xpress.data(data_type='fcs', analysis='gamb_colu_arab_fun', microarray=False)
fc_data.head()

,,Tiefora_v_Ngousso,Gou_v_Moz,Ban_v_BanS,BanRe_v_BanS,Bak_v_Kisumu,VK7_v_Kisumu,Cameroon_v_Ngousso,Chad_v_Ngousso,Niger_v_Ngousso,Nigeria_v_Ngousso,...,Ghana_fun_v_Fang,Malawi_fun_v_Fang,Uganda_fun_v_Fang,Asendabo_v_Moz,Chewaka_v_Moz,Tolay_v_Moz,Ethiopia_v_Dongola,Bouake_gamb_unexp_v_Kisumu,Bouake_colu_unexp_v_Ngousso,BusiaSurvivors_v_Kisumu
GeneID,GeneName,,,,,,,,,,,,,,,,,,,,,
AGAP007364,NaN,-2.61,-0.14,-1.02,1.32,0.42,0.89,-1.03,0.12,-1.44,-1.00,...,-0.04,0.41,-0.06,0.69,1.02,0.65,-1.10,-0.90,-2.00,1.46
AGAP010071,NaN,-2.32,0.31,-2.30,-0.37,-0.36,-0.59,-1.86,-1.82,-1.66,-1.71,...,0.58,0.41,0.67,-0.50,-0.31,-0.24,-0.48,0.14,-2.44,-0.05
AGAP007774,NaN,-1.77,-0.61,-0.93,-0.20,-0.17,-0.46,-0.11,-0.06,-0.12,-0.11,...,-0.04,-0.16,0.02,-0.93,-0.13,-0.85,-0.52,-0.29,-1.25,1.29
AGAP005809,NaN,-2.01,-0.18,-1.80,0.10,-1.06,-1.50,-0.46,0.25,-0.18,-0.04,...,0.18,0.28,0.20,0.52,0.45,0.11,0.75,-0.19,0.09,-0.26
AGAP006191,Cht24,3.89,-1.91,2.37,0.69,-1.38,1.94,5.46,5.67,5.43,4.95,...,-1.25,-2.90,-0.67,-0.46,-3.44,-1.31,6.59,-0.53,5.95,0.63

In [8]:
### load pval data
pvals_data = xpress.data(data_type='pvals', analysis='gamb_colu_arab_fun', microarray=False)
pvals_data.head()

,Tiefora_v_Ngousso,Gou_v_Moz,Ban_v_BanS,BanRe_v_BanS,Bak_v_Kisumu,VK7_v_Kisumu,Cameroon_v_Ngousso,Chad_v_Ngousso,Niger_v_Ngousso,Nigeria_v_Ngousso,...,Ghana_fun_v_Fang,Malawi_fun_v_Fang,Uganda_fun_v_Fang,Asendabo_v_Moz,Chewaka_v_Moz,Tolay_v_Moz,Ethiopia_v_Dongola,Bouake_gamb_unexp_v_Kisumu,Bouake_colu_unexp_v_Ngousso,BusiaSurvivors_v_Kisumu
GeneID,,,,,,,,,,,,,,,,,,,,,
AGAP007364,0.0,0.719,0.003,0.000,0.028,0.009,0.000,0.786,0.014,0.005,...,0.908,0.137,0.792,0.007,0.001,0.046,0.000,0.003,0.000,0.000
AGAP010071,0.0,0.212,0.000,0.147,0.001,0.000,0.000,0.000,0.000,0.000,...,0.002,0.269,0.001,0.008,0.110,0.252,0.198,0.426,0.000,0.721
AGAP007774,0.0,0.000,0.000,0.337,0.243,0.000,0.734,0.886,0.683,0.510,...,0.823,0.549,0.966,0.002,0.725,0.001,0.027,0.169,0.000,0.000
AGAP005809,0.0,0.313,0.000,0.577,0.000,0.000,0.094,0.282,0.552,0.891,...,0.305,0.056,0.083,0.000,0.004,0.519,0.000,0.116,0.297,0.000
AGAP006191,0.0,0.019,0.001,0.397,0.000,0.000,0.000,0.000,0.000,0.000,...,0.006,0.002,0.595,0.239,0.000,0.001,0.000,0.499,0.000,0.321

In [7]:
## load fold-change data including ir-tex data
fc_data = xpress.data(data_type='fcs', analysis='gamb_colu_arab_fun', microarray=True)
fc_data.head()

,,Tiefora_v_Ngousso,Gou_v_Moz,Ban_v_BanS,BanRe_v_BanS,Bak_v_Kisumu,VK7_v_Kisumu,Cameroon_v_Ngousso,Chad_v_Ngousso,Niger_v_Ngousso,Nigeria_v_Ngousso,...,VK72011,TiassaleMali,TiassaleOkyero,Tiassale2011,KovieOkyero,KovieMalanville,Youande,Hai,Muheza,Dar
GeneID,GeneName,,,,,,,,,,,,,,,,,,,,,
AGAP007364,NaN,-2.61,-0.14,-1.02,1.32,0.42,0.89,-1.03,0.12,-1.44,-1.00,...,0.245222,-0.376676,-0.489180,-2.186641,0.129679,0.772714,-1.025643,-2.619945,-0.789822,-1.846193
AGAP010071,NaN,-2.32,0.31,-2.30,-0.37,-0.36,-0.59,-1.86,-1.82,-1.66,-1.71,...,0.524025,0.017025,-0.195054,-0.725889,-0.078788,-0.094196,-0.016569,-0.075151,0.088686,0.034012
AGAP007774,NaN,-1.77,-0.61,-0.93,-0.20,-0.17,-0.46,-0.11,-0.06,-0.12,-0.11,...,-0.323672,0.220202,0.151694,-0.212418,-0.202592,-0.056531,-0.152393,0.784885,0.296350,0.080504
AGAP005809,NaN,-2.01,-0.18,-1.80,0.10,-1.06,-1.50,-0.46,0.25,-0.18,-0.04,...,0.029106,0.012453,0.120100,-0.037363,0.523589,0.607558,0.046630,-0.407620,0.005432,-0.338576
AGAP006191,Cht24,3.89,-1.91,2.37,0.69,-1.38,1.94,5.46,5.67,5.43,4.95,...,-1.600238,-0.295561,0.486746,1.081423,0.039556,-0.042103,-2.147031,-0.010618,0.078893,0.022758

In [10]:
## load metadata
comparisons_df = xpress.metadata(analysis='gamb_colu_arab_fun', microarray=True)
comparisons_df

,comparison,resistant,susceptible,species,country,latitude,longitude,technology
0,Tiefora_v_Ngousso,Tiefora,Ngousso,coluzzii,Burkina Faso,10.63080,-4.75890,rnaseq
1,Gou_v_Moz,Gou,Moz,arabiensis,Burkina Faso,10.63080,-4.75890,rnaseq
2,Ban_v_BanS,Ban,BanS,coluzzii,Burkina Faso,10.63080,-4.75890,rnaseq
3,BanRe_v_BanS,BanRe,BanS,coluzzii,Burkina Faso,10.63080,-4.75890,rnaseq
4,Bak_v_Kisumu,Bak,Kisumu,gambiae,Burkina Faso,10.63080,-4.75890,rnaseq
5,VK7_v_Kisumu,VK7,Kisumu,coluzzii,Burkina Faso,11.41170,-4.36277,rnaseq
6,Cameroon_v_Ngousso,Cameroon,Ngousso,coluzzii,Cameroon,10.84400,14.90000,rnaseq
7,Chad_v_Ngousso,Chad,Ngousso,coluzzii,Chad,12.10000,15.03000,rnaseq
8,Niger_v_Ngousso,Niger,Ngousso,coluzzii,Niger,13.70000,7.98000,rnaseq
9,Nigeria_v_Ngousso,Nigeria,Ngousso,coluzzii,Nigeria,9.98750,12.36050,rnaseq
10,Agboville_v_Mali,Agboville,Mali,coluzzii,Cote d'Ivoire,5.94480,-4.21468,rnaseq
11,Agboville_v_Ngousso,Agboville,Ngousso,coluzzii,Cote d'Ivoire,5.94480,-4.21468,rnaseq
12,Dabou_v_Mali,Dabou,Mali,coluzzii,Cote d'Ivoire,5.33100,-4.37200,rnaseq
13,Dabou_v_Ngousso,Dabou,Ngousso,coluzzii,Cote d'Ivoire,5.33100,-4.37200,rnaseq
14,Tiassale_v_Mali,Tiassale,Mali,coluzzii,Cote d'Ivoire,5.90060,-4.83500,rnaseq
15,Tiassale_v_Ngousso,Tiassale,Ngousso,coluzzii,Cote d'Ivoire,5.90060,-4.83500,rnaseq
16,Cam_fun_v_Fang,Cam_fun,Fang,funestus,Cameroon,6.08000,11.47000,rnaseq
17,Fumoz_v_Fang,Fumoz,Fang,funestus,Mozambique,-22.77488,33.80900,rnaseq
18,Ghana_fun_v_Fang,Ghana_fun,Fang,funestus,Ghana,5.93300,-1.60000,rnaseq
19,Malawi_fun_v_Fang,Malawi_fun,Fang,funestus,Malawi,-16.01000,34.78330,rnaseq
20,Uganda_fun_v_Fang,Uganda_fun,Fang,funestus,Uganda,0.67700,34.18400,rnaseq
21,Asendabo_v_Moz,Asendabo,Moz,arabiensis,Ethiopia,7.77280,37.22979,rnaseq
22,Chewaka_v_Moz,Chewaka,Moz,arabiensis,Ethiopia,8.89366,36.15594,rnaseq
23,Tolay_v_Moz,Tolay,Moz,arabiensis,Ethiopia,8.35600,37.34090,rnaseq
24,Ethiopia_v_Dongola,Ethiopia,Dongola,arabiensis,Ethiopia,7.77280,37.22979,rnaseq
25,Bouake_gamb_unexp_v_Kisumu,Bouake_gamb_unexp,Kisumu,gambiae,Cote d'Ivoire,7.73167,-5.00010,rnaseq
26,Bouake_colu_unexp_v_Ngousso,Bouake_colu_unexp,Ngousso,coluzzii,Cote d'Ivoire,7.73167,-5.00010,rnaseq
27,BusiaSurvivors_v_Kisumu,BusiaSurvivors,Kisumu,gambiae,Uganda,0.47648,34.09281,rnaseq
28,Nkolondom,Nkolondom,NaN,gambiae,Cameroon,NaN,NaN,microarray
29,Garre,Garre,NaN,coluzzii,Cameroon,NaN,NaN,microarray
30,Messa,Messa,NaN,coluzzii,Cameroon,NaN,NaN,microarray
31,Bioko,Bioko,NaN,coluzzii,Equatorial Guinea,NaN,NaN,microarray
32,Kitwe,Kitwe,NaN,gambiae,Zambia,NaN,NaN,microarray
33,Bouake,Bouake,NaN,coluzzii,Cote d'Ivoire,NaN,NaN,microarray
34,MBe,MBe,NaN,coluzzii,Cote d'Ivoire,NaN,NaN,microarray
35,Tiassale,Tiassale,NaN,coluzzii,Cote d'Ivoire,NaN,NaN,microarray
36,PembaMoz,PembaMoz,NaN,arabiensis,Tanzania,NaN,NaN,microarray
37,PembaUnguja,PembaUnguja,NaN,arabiensis,Tanzania,NaN,NaN,microarray
38,PembaDar,PembaDar,NaN,arabiensis,Tanzania,NaN,NaN,microarray
39,WadMedani,WadMedani,NaN,arabiensis,Sudan,NaN,NaN,microarray
40,VK6,VK6,NaN,coluzzii,Burkina Faso,NaN,NaN,microarray
41,Banfora,Banfora,NaN,coluzzii,Burkina Faso,NaN,NaN,microarray
42,Tiefora13,Tiefora13,NaN,gambiae,Burkina Faso,NaN,NaN,microarray
43,Tiefora14,Tiefora14,NaN,gambiae,Burkina Faso,NaN,NaN,microarray
44,JinjaMoz,JinjaMoz,NaN,arabiensis,Uganda,NaN,NaN,microarray
45,JinjaDong,JinjaDong,NaN,arabiensis,Uganda,NaN,NaN,microarray
46,DSSBA,DSSBA,NaN,arabiensis,Burkina Faso,NaN,NaN,microarray
47,Tengrela,Tengrela,NaN,coluzzii,Burkina Faso,NaN,NaN,microarray
48,VK72012,VK72012,NaN,coluzzii,Burkina Faso,NaN,NaN,microarray
49,VK72011,VK72011,NaN,coluzzii,Burkina Faso,NaN,NaN,microarray
50,TiassaleMali,TiassaleMali,NaN,coluzzii,Cote d'Ivoire,NaN,NaN,microarray
51,TiassaleOkyero,TiassaleOkyero,NaN,coluzzii,Cote d'Ivoire,NaN,NaN,microarray
52,Tiassale2011,Tiassale2011,NaN,coluzzii,Cote d'Ivoire,NaN,NaN,microarray
53,KovieOkyero,KovieOkyero,NaN,coluzzii,Togo,NaN,NaN,microarray
54,KovieMalanville,KovieMalanville,NaN,coluzzii,Togo,NaN,NaN,microarray
55,Youande,Youande,NaN,gambiae,Cameroon,NaN,NaN,microarray
56,Hai,Hai,NaN,arabiensis,Tanzania,NaN,NaN,microarray
57,Muheza,Muheza,NaN,arabiensis,Tanzania,NaN,NaN,microarray
58,Dar,Dar,NaN,arabiensis,Tanzania,NaN,NaN,microarray